# -*- coding: utf-8 -*-
"""attractions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aExJqUCLIPcFcQbQ9KEmo8xrAvFZ_bJI
"""

#from google.colab import drive
#drive.mount('/content/drive', force_remount=True)

#!ls

import pandas as pd
import numpy as np
import email

data = pd.read_csv('/content/drive/My Drive/attractions.csv')
data

data.fillna(data.mean(), inplace=True)

data

data.round({'price': 2, 'rating': 1})

print(data.head())
# !pwd
# # !cd ..

data.to_csv('attractions.csv', index=False)


data['category'].unique()