# -*- coding: utf-8 -*-
"""Hotels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kFRKwuqGibfKIw3xYtAXnIBfkEUMLeB5
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

hotel_df = pd.read_csv('/content/drive/My Drive/hotel_info.csv')

hotel_df = hotel_df.drop(['hotel_experience'], axis=1)

hotel_df.fillna(hotel_df.mean(), inplace=True)

hotel_df.round({'hotel_rating': 1, 'price': 2})

hotel_df.replace('[]', np.NaN, inplace=True)

hotel_df = hotel_df.dropna()

hotel_df = hotel_df.reset_index(drop=True)

hotel_df.to_csv('result.csv', index=False)