# -*- coding: utf-8 -*-
"""yelp_business.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6LND3yEO7sAOXVT4q97sAhzI4qWXSGQ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/My Drive/yelp_business.csv')

df = df.drop(['neighborhood', 'state', 'latitude', 'longitude'], axis=1)

df.drop(df[df['is_open'] == 0].index, inplace=True)

df = df.drop(['business_id'], axis=1)

df = df[df['categories'].str.contains("Restaurants", case=False)]

df = df[df['categories'].str.contains("Food", case=False)]

df = df.reset_index(drop=True)

df.to_csv('dataset.csv', index=False)